apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-processor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/raghav1902/ai-task-processor-infra.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: task-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
