apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - frontend.yaml
  - backend.yaml
  - worker.yaml
  - mongo.yaml
  - redis.yaml
  - ingress.yaml
  - hpa.yaml
